# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-07 02:30
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dumpsters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dumpster',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=None, srid=4326),
            preserve_default=False,
        ),
    ]
