# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-10 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dumpsters", "0004_auto_20160508_0832"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dumpster",
            name="created",
            field=models.DateTimeField(auto_created=True, null=True),
        ),
    ]
