# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-02 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dumpsters", "0009_dumpster_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="voting",
            name="user",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
