name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  POSTGRES_USER: postgres
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres
  SECRET_KEY: secret
  DATABASE_URL: postgresql://$POSTGRES_USER:$POSTGRES_PASSWORD@localhost:5432/$POSTGRES_DB

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ '3.10' ]

    services:
      db_service:
        image: postgis/postgis
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies (geospatial libraries)
        run: |
          sudo apt-get update
          sudo apt-get install binutils libproj-dev gdal-bin
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pipenv wheel
      - name: Install Python Dependencies
        run: |
          pipenv install --deploy --dev
      - name: pre-commit
        run: |
          pipenv run pre-commit install
          pipenv run pre-commit run --all-files
      - name: Migrate database
        run: |
          pipenv run python manage.py migrate
      - name: Run Tests
        run: |
          pipenv run pytest
