name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db_service:
        image: postgis/postgis
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies (geospatial libraries)
        run: |
          sudo apt-get update
          sudo apt-get install binutils libproj-dev gdal-bin
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
      - name: Install Python Dependencies
        run: |
          uv sync --locked --all-groups
      - name: Migrate database
        run: |
          uv run python manage.py migrate
        env:
          SECRET_KEY: secret
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
      - name: Run Tests
        env:
          SECRET_KEY: secret
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres
        run: |
          uv run pytest
